author = "Max Kang"
description = "A software engineer who believes less is more — in code, life, and everything in between."
menu_item_separator = " - "

[[social]]
      icon = "brand-github"
      name = "Github"
      url = "https://github.com/maxkangdev"

[[social]]
      icon = "brand-readdotcv"
      name = "Github"
      url = "/en/cv"