baseURL = 'https://maxkangdev.github.io'
title = 'My New Hugo Site'
theme = "hugo-theme-m10c"
googleAnalytics = "G-KHH0NVNV32"

defaultContentLanguage = 'ko'
defaultContentLanguageInSubdir = true
[languages]
  [languages.ko]
    contentDir = 'content/ko'
    disabled = false
    languageCode = 'ko-KR'
    languageDirection = 'ltr'
    languageName = 'Korean'
    title = '맥스의 블로그'
    weight = 1

  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = "Max's Blog"
    weight = 2

[params.style]
  darkestColor = "#242930"
  darkColor = "#1b1b1e"
  lightColor = "#aeb0b1"
  lightestColor = "#cbcbcb"
  primaryColor = "#8a5cf4"

[params.style.lightMode]
  darkestColor = "#f0f0f0"
  darkColor = "#ffffff"
  lightColor = "#34343c"
  lightestColor = "#000000"
  primaryColor = "#8a5cf4"
